services:
  stat-service:
    build: ./stats-service/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - statsdb
    environment:
      - DB_NAME=statistic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - DB_HOST=statsdb
      - DB_PORT=5432

  statsdb:
    image: postgres:16.1
    container_name: statsdb
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=statistic
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  main-service:
    container_name: main-service
    build: ./main-service
    ports:
      - "8080:8080"
    depends_on:
      - stat-service
      - ewmdb
    environment:
      - DB_NAME=ewm
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - DB_HOST=ewmdb
      - DB_PORT=5432

  ewmdb:
    image: postgres:16.1
    container_name: ewmdb
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

